apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogging-app-deployment
spec:
  selector:
    matchLabels:
      app: blogging-app
  replicas: 2
  template:
    metadata:
      labels:
        app: blogging-app
    spec:
      containers:
        - name: blogging-app
          image: adijaiswal/blogging-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: blogging-app-ssvc
spec:
  selector:
    app: blogging-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer